services:
  client:
    image: flaviare1s/gerenciador-alunos-client:latest
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    image: flaviare1s/gerenciador-alunos-server:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/escola_db
      CORS_ORIGIN: http://localhost
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escola_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d escola_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: